import UIKit
import SnapKit

final class EULAViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        modalPresentationStyle = .overFullScreen
        view.backgroundColor = UIColor.black.withAlphaComponent(0.38)

        let card = UIView()
        card.backgroundColor = .white
        card.layer.cornerRadius = 22
        card.layer.masksToBounds = true
        view.addSubview(card)
        card.snp.makeConstraints {
            $0.center.equalToSuperview()
            $0.leading.trailing.equalToSuperview().inset(22)
            $0.height.equalTo(644).priority(.high)
            $0.height.lessThanOrEqualTo(view.safeAreaLayoutGuide.snp.height).offset(-20)
        }

        let title = UILabel.appLabel("EULA", size: 18, weight: .semibold)
        card.addSubview(title)
        title.snp.makeConstraints { $0.top.equalToSuperview().offset(39); $0.leading.trailing.equalToSuperview().inset(19) }

        let body = UILabel()
        body.text = """
        Welcome to Yorzi to create a positive, safe and standardized space for beauty and meaningful sharing, the following content is strictly prohibited on the app:
        1. Any content involving child harm, pornography and other materials detrimental to minors’ physical and mental health, including but not limited to texts, images, videos or comments that insult, defame or improperly use minors’ portraits and information.
        2. False and harmful public information, including false content generated by AI or other means that disrupts public order, especially fake beauty tutorials, misleading skincare and makeup guidance, and false public opinion content.
        3. Violent content, cyber bullying, and any content that promotes pornography, illegal acts or disrupts the network ecological environment. Specifically, it is forbidden to upload pornographic, violent, bloody content, or use beauty sharing, comment and interaction functions to conduct cyber bullying and spread inappropriate information.
        If any of the above violations are detected, your uploaded works, comments and other published content will be deleted, and your account will be restricted or banned. By clicking the confirmation button, you agree to abide by the Terms of Use and Privacy Policy of Yorzi.
        """
        body.font = .systemFont(ofSize: 11, weight: .regular)
        body.textColor = AppTheme.secondary
        body.numberOfLines = 0
        let paragraph = NSMutableParagraphStyle()
        paragraph.lineSpacing = 2
        body.attributedText = NSAttributedString(string: body.text ?? "", attributes: [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: AppTheme.secondary,
            .paragraphStyle: paragraph
        ])

        let bodyScroll = UIScrollView()
        bodyScroll.showsVerticalScrollIndicator = false
        bodyScroll.addSubview(body)
        card.addSubview(bodyScroll)
        bodyScroll.snp.makeConstraints {
            $0.top.equalTo(title.snp.bottom).offset(9)
            $0.leading.trailing.equalToSuperview().inset(19)
            $0.bottom.equalToSuperview().inset(83)
        }
        body.snp.makeConstraints {
            $0.edges.equalTo(bodyScroll.contentLayoutGuide)
            $0.width.equalTo(bodyScroll.frameLayoutGuide)
        }

        let cancel = UIButton.outline("Cancel")
        cancel.configuration?.contentInsets = .zero
        cancel.configuration?.titleTextAttributesTransformer = UIConfigurationTextAttributesTransformer { var attributes = $0; attributes.font = .systemFont(ofSize: 12, weight: .semibold); return attributes }
        let agree = UIButton.primary("Agree")
        agree.configuration?.baseBackgroundColor = AppTheme.lavender
        agree.configuration?.contentInsets = .zero
        agree.configuration?.titleTextAttributesTransformer = UIConfigurationTextAttributesTransformer { var attributes = $0; attributes.font = .systemFont(ofSize: 12, weight: .semibold); return attributes }
        let buttons = UIStackView(arrangedSubviews: [cancel, agree])
        buttons.axis = .horizontal
        buttons.spacing = 8
        buttons.distribution = .fillEqually
        card.addSubview(buttons)
        buttons.snp.makeConstraints { $0.leading.trailing.bottom.equalToSuperview().inset(19); $0.height.equalTo(44) }

        agree.addAction(UIAction { _ in
            DataRepository.shared.acceptEULA()
            AppRouter.showWelcome()
        }, for: .touchUpInside)
        cancel.addAction(UIAction { _ in exit(0) }, for: .touchUpInside)
    }
}
